apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx-namespace
  labels:
    label: nginx-pod-label
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: ubuntu-container
    image: ubuntu:local
    imagePullPolicy: Never
    command: ["sleep"]
    args: ["1000"]
