apiVersion: v1
kind: Service
metadata:
  name: nginx-replicaset-service
spec:
  type: NodePort
  selector:
    label: nginx-replicaset-label
  ports:
    - protocol: TCP
      port: 80
      name: http
